### PR TITLE
Lab1

### PR DESCRIPTION
**Pull request by IgorBanin**
Write some comments on my lab report! @elocj

### CODE REVIEW

**Comment by elocj** [comment]
@IgorBanin Hey I can't see you're ipynb in github I think the professor might have also wanted a html file?

**Comment by IgorBanin** [comment]
@elocj i went ahead and pushed the lab1 in html format under the lab1 branch. Everything is visible to me, let me know if there are any more issues.

**Comment by elocj** [comment]
Hey Igor, really nice lab! I just had a couple comments. The first of which is "A little statistics (1D)"  in which we discuss negative values. You interpreted that as the negative values passed into the ppf. I interpreted it as the negative value passed into cdf and how negative values just mean the integral to the right of a given point. Feel free to let me know if you feel this is incorrect. Additionally, I think you might be missing the last part where you are discussing why you parameter values can be continuous. I think you briefly discuss but don't share specifically why this is allowed. Lastly I think you need some implications that a discrete probability and sigma entails

**Comment by IgorBanin** [comment]
For 1D it says to explain the meaning of the minus sign that appears. I interpreted it as the negative values that appear from running the ppf function. I think both interpretations are valid, i think they just want us to mention that a negative sigma implies a cumulative probability to the left of the mean.

**Comment by IgorBanin** [comment]
@oliviatessa I have finished adding final comments to my lab report !

**Pull request merged**
