### PR TITLE
Lab3

### PR DESCRIPTION
**Pull request by IgorBanin**
@elocj some parts are still missing, but feedback is appreciated !

### CODE REVIEW

**Comment by elocj** [comment]
Hey Igor, the lab is coming along well judging from your part 1. One thing I want to add is that you might be missing your truth table in the version I have. It seems like your false/true positive/negative are missing. I'm also confused as to why you are calculating the mean and standard deviation values for the new distribution because as Olivia discussed it would be best to rather just find the 5 sigma point through probabilities. I liked your explanation about why there are some omissions or mistakes of commission with the data. I would just recommend adding an explanation for why we're finding 5 sigma with probability instead of recalculated mean and stdev but good work!

**Comment by IgorBanin** [comment]
I realize it's not completely necessary but the mean and standard deviation calculations were just me exploring the bounds of the problem, and that we shouldn't use bad data in calculation of mean and standard deviation. 5sigma point probabilities are discussed right after !

**Comment by IgorBanin** [comment]
@oliviatessa all files are in !

**Comment by IgorBanin** [comment]
@oliviatessa my writeups do not use Latex(i do not know how to use late), do i still need to reupload my lab as pdf?

**Comment by oliviatessa** [comment]
Nope that’s fine!

**Comment by oliviatessa** [comment]
Hi Igor, 

Here are my comments on your lab 3: 

- Don't forget your lab partner's name. 

P.1 
- Why did you choose 5 sigma as your threshold? 
- Great job considering other ways to remove the bad data! 

P.2 
- For this problem, the amplitude fluctuations of a 2D Gaussian can be modeled as a Rayleigh distribution (Blue Book hint from Miguel). The fluctuation distance is the x-value associated with 5sigma on the Rayleigh distribution. 

P.3 
- All the math is correct in this problem, but it would be good to discuss finding signals on the left tail of your distribution, considering thus far we've only worked on the right side of the distribution. Just a few words on this would be great. 

Best, 
Olivia

**Pull request closed without merging**
